apiVersion: v1
kind: Service
metadata:
  name: neural-glass
  labels:
    app: neural-glass
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: neural-glass
