apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neural-glass-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/johnpiklis/templatemo_597_neural_glass.git"
    targetRevision: main
    path: "k8s"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
