name: build-and-push

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: write


env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: neural-glass
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set image vars
      run: |
        IMAGE_TAG=${GITHUB_SHA::8}
        ECR_REGISTRY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        IMAGE_URI=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t $IMAGE_URI .

    - name: Push to ECR
      run: docker push $IMAGE_URI

    - name: Update k8s deployment image
      run: |
        git config user.name "${{ secrets.USER_NAME }}"
        git config user.email "${{ secrets.USER_EMAIL }}"
        sed -i "s|IMAGE_PLACEHOLDER|${IMAGE_URI}|g" k8s/deployment.yaml
        git add k8s/deployment.yaml
        git commit -m "ci: deploy image ${IMAGE_URI}" || echo "no changes to commit"
        git push origin HEAD:main
        
  
    - name: Display resulting image
      run: echo "Pushed ${IMAGE_URI}"
